
package com.persistent;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookImpl", targetNamespace = "http://persistent.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookImpl {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "addBooksOps", targetNamespace = "http://persistent.com/", className = "com.persistent.AddBooksOps")
    @ResponseWrapper(localName = "addBooksOpsResponse", targetNamespace = "http://persistent.com/", className = "com.persistent.AddBooksOpsResponse")
    public void addBooksOps();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "getBooks", targetNamespace = "http://persistent.com/", className = "com.persistent.GetBooks")
    @ResponseWrapper(localName = "getBooksResponse", targetNamespace = "http://persistent.com/", className = "com.persistent.GetBooksResponse")
    public void getBooks();

    /**
     * 
     * @param arg1
     * @param bookName
     */
    @WebMethod
    @RequestWrapper(localName = "addBook", targetNamespace = "http://persistent.com/", className = "com.persistent.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://persistent.com/", className = "com.persistent.AddBookResponse")
    public void addBook(
        @WebParam(name = "Book_Name", targetNamespace = "")
        String bookName,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param bookName
     * @return
     *     returns java.lang.String
     * @throws CustomException_Exception
     */
    @WebMethod
    @WebResult(name = "Book_Author_Name", targetNamespace = "")
    @RequestWrapper(localName = "getBookAuthor", targetNamespace = "http://persistent.com/", className = "com.persistent.GetBookAuthor")
    @ResponseWrapper(localName = "getBookAuthorResponse", targetNamespace = "http://persistent.com/", className = "com.persistent.GetBookAuthorResponse")
    public String getBookAuthor(
        @WebParam(name = "Book_Name", targetNamespace = "")
        String bookName)
        throws CustomException_Exception
    ;

}
